#ifndef _qi_component_types_h_
#define _qi_component_types_h_

namespace QI{ 

/** Type of intersections */
typedef enum {
			
	INTER_TYPE_UNDEFINED			=	9999, /** No value */
	INTER_TYPE_SMOOTH_QUARTIC_BRANCH_1	=	0,
	INTER_TYPE_SMOOTH_QUARTIC_BRANCH_2	=	1,
	INTER_TYPE_NODAL_QUARTIC		=	2,
	INTER_TYPE_CUSPIDAL_QUARTIC		=	3,
	INTER_TYPE_CUBIC			=	4,
	INTER_TYPE_CONIC			=	5,
	INTER_TYPE_LINE				=	6,
	INTER_TYPE_LINES_WITH_CONSTRAINT	=	7,
	INTER_TYPE_POINT			=	8,
	INTER_TYPE_SMOOTH_QUADRIC		=	9,
	INTER_TYPE_CONE				=	10,
	INTER_TYPE_PAIR_OF_PLANES		=	11,
	INTER_TYPE_PLANE			=	12,
	INTER_TYPE_UNIVERSE			=	13

}InterComponentType;

/** Euclidean types for input quadrics */
typedef enum {

	EUCL_INPUT_TYPE_UNDEFINED			=	9999,

	EUCL_INPUT_TYPE_EMPTY				=	0,

	EUCL_INPUT_TYPE_ELLIPSOID			=	1,
	EUCL_INPUT_TYPE_HYPERBOLOID_OF_TWO_SHEETS	=	2,
	EUCL_INPUT_TYPE_ELLIPTIC_PARABOLOID		=	3,

	EUCL_INPUT_TYPE_POINT				=	4,
	EUCL_INPUT_TYPE_EMPTY_ONE_POINT_AT_INF		=	5,

	EUCL_INPUT_TYPE_HYPERBOLOID_OF_ONE_SHEET	=	6,
	EUCL_INPUT_TYPE_HYPERBOLIC_PARABOLOID		=	7,

	EUCL_INPUT_TYPE_CONE				=	8,
	EUCL_INPUT_TYPE_ELLIPTIC_CYLINDER		=	9,
	EUCL_INPUT_TYPE_HYPERBOLIC_CYLINDER		=	10,
	EUCL_INPUT_TYPE_PARABOLIC_CYLINDER		=	11,

	EUCL_INPUT_TYPE_LINE				=	12,
	EUCL_INPUT_TYPE_EMPTY_ONE_LINE_AT_INF		=	13,

	EUCL_INPUT_TYPE_INTERSECTING_PLANES		=	14,
	EUCL_INPUT_TYPE_PARALLEL_PLANES			=	15,
	EUCL_INPUT_TYPE_SIMPLE_PLANE			=	16,

	EUCL_INPUT_TYPE_DOUBLE_PLANE			=	17,
	EUCL_INPUT_TYPE_EMPTY_DOUBLE_PLANE_AT_INF	=	18,

	EUCL_INPUT_TYPE_UNIVERSE			=	19

}InputEuclideanType;

} /** End namespace QI */

#endif

